### ISSUE TITLE
Feature Request - MNK

### ISSUE THREAD

**Issue by Evolutious** [PrincessRTFM/XIVComboPlugin#10]
Good day again! 

I was wondering if it would be possible to expand the feature you already have 'Perfect Balance Feature' as follows:
- Add: a level check for this feature (or add a note to the feature description indicating that you need to be level 60 or higher to use this feature) since you need to be level 60 to gain access to Masterful Blitz and build the Beast Chakras (this is mostly because of the second bullet request and assuming you do not already have one in place)
- Add: Replace Perfect Balance with Masterful Blitz while you have the 'Perfect Balance' buff (this will cause issues for players that are under level 60 since you do not have access to Masterful Blitz until then)
- Maintain: Replace Perfect Balance with Masterful Blitz when you have 3 Beast Chakras

Reasoning for the request; There should be no instance where you would need to activate Perfect Balance while you have a Perfect Balance buff active.

The effect of this would be that you hit Perfect Balance, it activates the Perfect Balance buff and immediately changes to Masterful Blitz and remains in that state until you either loose the Perfect Balance buff (buff timer runs out) or you use Masterful Blitz as a result of having the 3 Beast Chakras.

If the level 60 check is not there, then this could cause issues for players under level 60 since you gain access to Perfect Balance at level 50 but you don't gain access to Masterful Blitz until level 60.

**Comment by Evolutious** [comment]
I took a brief look at your code and I believe all that should be required for this is as follows:

File: Combos / MNK.cs

Line: 182
Replace: `if (!gauge.BeastChakra.Contains(BeastChakra.NONE))`
With: `if (!gauge.BeastChakra.Contains(BeastChakra.NONE)) || level < MNK.Levels.MasterfulBlitz || SelfHasEffect(MNK.Buffs.PerfectBalance)`

**Comment by Evolutious** [comment]
I took a brief look at your code and I believe all that should be required for this is as follows:

File: Combos / MNK.cs

Line: 182
Replace: `if (!gauge.BeastChakra.Contains(BeastChakra.NONE))`
With: `if (level >= MNK.Levels.MasterfulBlitz && (!gauge.BeastChakra.Contains(BeastChakra.NONE) || SelfHasEffect(MNK.Buffs.PerfectBalance)))`

**Comment by PrincessRTFM** [comment]
You are my favourite kind of person. Added and releasing now.

**Comment by Evolutious** [comment]
Tested it and it works perfectly! Thank you.
