### ISSUE TITLE
Debug 3913 is partially broken for RPR

### ISSUE THREAD

**Issue by Reytholian** [PrincessRTFM/XIVComboPlugin#107]
I was testing on a dummy and noticed that when entering Enshroud I only get one of the Gibbet or Gallows in this case Void or Cross Reaping. It doesn't change the action to the enhanced version of the other one until I enter Enshroud again. Gibbet and Gallows does alternate between the two as normal but the Enshroud phase only shows one at a time and alternates when the effect ends and going back into it.

**Comment by PrincessRTFM** [comment]
What level are you at?

**Comment by Reytholian** [comment]
level 92

**Comment by PrincessRTFM** [comment]
Mm, either a change in DT broke something (possibly Dalamud's reference to the job gauge) or reaching 92 did it. I've got RPR on 90, so I'll see what I can figure out. Executing the Enshroud action at 92 is supposed to _also_ grant Oblatio, but there _shouldn't_ be any other changes, so I'll have to dig around in the replacer logic. Can you screenshot your settings for RPR?

**Comment by Reytholian** [comment]
![20240710153556_1](https://github.com/PrincessRTFM/XIVComboPlugin/assets/17226211/1c4ad5e9-ae6c-40ba-9e0f-4dcf9a68732b)
![20240710153549_2](https://github.com/PrincessRTFM/XIVComboPlugin/assets/17226211/9b4a35d5-12ef-4f6c-a8af-a80da1aee27a)

You can see in both images that the Enhanced Gallows does work as stated with the plugin setting but for some reason Enhanced Cross Reaping doesn't replace Void Reaping despite having the buff.

**Comment by PrincessRTFM** [comment]
For some reason, the Enhanced Cross Reaping effect isn't actually being _checked_ anywhere, so I guess I found the problem.

I tested briefly on a striking dummy and I _think_ I've fixed it now, but this replacer is a little complicated. Please let me know if it's still broken!

**Comment by Reytholian** [comment]
Just tested it and confirmed that it does work!

**Comment by PrincessRTFM** [comment]
Fantastic!
