### ISSUE TITLE
Feature Adjustment - MNK

### ISSUE THREAD

**Issue by Evolutious** [PrincessRTFM/XIVComboPlugin#11]
Good day! I am looking at the changes I had requested, and while they work as requested, they are not very optimal. Would you mind please adding a time check to the Disciplined Fist buff and Demolish debuff so the actions are changed only if the buff/debuff has more than 5s remaining on them?

I was thinking something like this, but I will leave the final results up to you if you prefer a better way to do it! (assuming you are cool with this ofc)

File: Combos\MNK.cs

Line 209; Change:
`return level < MNK.Levels.TwinSnakes || SelfHasEffect(MNK.Buffs.DisciplinedFist)`
To:
`Status? fist = SelfFindEffect(MNK.Buffs.DisciplinedFist);`
`return level < MNK.Levels.TwinSnakes || (fist.RemainingTime != null && fist.RemainingTime > 5)`

Line 222; Change:
`return level < MNK.Levels.Demolish || TargetHasOwnEffect(MNK.Debuffs.Demolish)`
To:
`Status? demo = TargetFindOwnEffect(MNK.Debuffs.Demolish);`
`return level < MNK.Levels.Demolish || (demo.RemainingTime != null && demo.RemainingTime > 5)`

Thank you!

**Comment by Spanglish1337** [comment]
@Evolutious is this for 1.94 GCD?

**Comment by Evolutious** [comment]
> @Evolutious is this for 1.94 GCD?

Yes.
