### ISSUE TITLE
Samurai Combo lvl92 up need its New 1st Attack "Gyofu"

### ISSUE THREAD

**Issue by GettinTrippi** [PrincessRTFM/XIVComboPlugin#111]
The Samurai attack "Hakaze" has been upgraded at level 92 to "Gyofu"

The Safe comboes you have at the moment still use level 1's Hakaze.

Gyofu procs the other attacks exactly like Hakaze does.

Gyofu -> Jinpu -> Gekko
Gyofu -> Shifu -> Kasha
Gyofu -> Yukikaze

It does not proc any additional effects.

(Hope I did this right!)

**Comment by GettinTrippi** [comment]
![Screenshot_1](https://github.com/user-attachments/assets/f3c8180c-6c15-46ed-abf7-29d79a77b79f)

**Comment by FrigidWalrus** [comment]
Ah, that's an easy enough fix. @PrincessRTFM is asleep currently, but I should have a fix out for it before she wakes up. Dalamud will likely be down for a bit, but by the time it comes back up, that SAM combo should work fine.

**Comment by FrigidWalrus** [comment]
Ok, fixed this. Just needed to change over the way it shows Hakaze. Now it should show Hakaze when below 92, and should auto-upgrade if at 92+.

**Comment by PrincessRTFM** [comment]
Got it ready and waiting for when the Dalamud devs announce they've got it working on the new patch

**Comment by GettinTrippi** [comment]
Seems to be working now 👌

**Comment by FrigidWalrus** [comment]
Alright, I think I'll need to rework the code on this. There's some lines that may not actually work with Gyofu. To be safe, I'm commenting out the SAM Combos we had released, as well as the options in the settings window. 

Thank you for bringing this to our attention, and I will work on this later tonight to see if I can get it to work correctly.

**Comment by GettinTrippi** [comment]
[https://cdn.discordapp.com/attachments/1048698292097273927/1262992407067234324/2024-07-17_00-39-53.mp4?ex=66989cd7&is=66974b57&hm=cbb9da1b7d70ffdad4f578dc36a5182875b1d4887f4465ee01bf4083afc1c3c8&](url)

I did a short video on the gyofu interactions at the moment. Hope it helps ^^

**Comment by GettinTrippi** [comment]
[2024-07-17 00-39-53.webm](https://github.com/user-attachments/assets/522597e2-f3aa-4663-8ec3-3344e8f51e03)

I did a quick video to show how it's working for me atm

**Comment by FrigidWalrus** [comment]
I literally just pushed a fix, and I can tell you have the old version, as you still have the Hissatsu feature down at the bottom. I commented that out, as I have no real idea if that's working correctly in all situations. 

Please update and test the combos, and see if they return correctly now.

**Comment by GettinTrippi** [comment]
Samurai's not in the list, I assume forgor to be reincluded

**Comment by PrincessRTFM** [comment]
It can take a few minutes for the build/deploy process to finish and the update to _actually_ be available. Please try updating again.

**Comment by GettinTrippi** [comment]
https://github.com/user-attachments/assets/c5ae94be-26ed-4a2a-8209-41b4a276b876

Seems to work as intended now, thank you <3
