### ISSUE TITLE
[NIN] Kazematoi Overcap/Management

### ISSUE THREAD

**Issue by ratzup** [PrincessRTFM/XIVComboPlugin#113]
Endwalker removed huton management and replaced it with Kazematoi. Armor crush grants 2 stacks while Aeolian Edge consumes 1.
Would love to suggest adding this option to help with Kazematoi management:

- Option for Aeolian Edge to fall back to armour crush when 0 stacks of Kazematoi
- Option for Armour crush to fall back to Aeolian Edge when 4 or 5 stacks of Kazematoi [to prevent overcap].
![image](https://github.com/user-attachments/assets/91300e35-a977-4d6a-932b-83c40cc640e5)

**Comment by PrincessRTFM** [comment]
I've been thinking about this, but I'm not sure if using those off-position is worth it, or if it's better to overcap when you can only reach the enemy's side, for example.

**Comment by ratzup** [comment]
I thought the same too but looking into it, overcapping on Kazematoi is a flat dps loss.
Aeolian Edge's default combo potency is 380, with 440 if landing positional.
But with each stack of Kazematoi it adds an additional 100+ potency which matches the flank combo potency of Armor crush 480.

**Potency with Kazematoi potency added:**
Aeolian Edge [No Positional] - 480
Aeolian Edge [With Positional] - 540

Armor Crushes potency:
Armor Crush [No Positional] - 420
Armor Crush [With Positional] - 480

Taken from https://maplespyder.github.io/NIN-Guide/2024/07/04/nin-DT-comprehensive-guide.html
![image](https://github.com/user-attachments/assets/3ddfb841-62e9-4b10-acc4-204a8fc47772)

**Comment by PrincessRTFM** [comment]
Got it, I'll see about implementing that then!
