### ISSUE TITLE
[MNK] Suggestion for Monk

### ISSUE THREAD

**Issue by ksledu** [PrincessRTFM/XIVComboPlugin#14]
Hello PrincessRTFM. Can you add some options in monk combo? please check picture below. It was from another xivcombo plugins. No offense. Thank you in advance.

![image](https://user-images.githubusercontent.com/96337656/150483088-9d2a243b-42bc-4a27-86b3-acc37a0eaad0.png)

**Comment by PrincessRTFM** [comment]
Currently, Dragon Kick is replaced with Bootshine when under Leaden Fist and Perfect Balance becomes Masterful Blitz with three beast chakra. I can add the requested feature, but which one should be prioritised if both are available? Likewise for the other two, what should Riddle of Fire become if it's on CD and neither Brotherhood nor Riddle of Wind are?

**Comment by ksledu** [comment]
Thanks for your reply. 
1. Masterful blitz is always more priority than bootshine while both are available 
2. Riddle of fire > brotherhodd > riddle of wind.  Riddle of fire is the king. ^_^ 
Thanks a lot.
