### ISSUE TITLE
Smart single target breaks RDM opener.

### ISSUE THREAD

**Issue by LaziestLou** [PrincessRTFM/XIVComboPlugin#16]
Hello, just wanted to raise a small issue that smart single target feature breaks the opener, as it changes verthunder into veraero, whereas the opener requires 2 consecutive insta-casted verthunders (verthunder into veraero dualcasted->swiftcast+acceleration->verthunder->verthunder->embolden+manafication->combo+verholy finisher).

My suggestion for this would be to let smart single target fully change verfire/verstone, but not touch verthunder/veraero, this would keep full button functionality but also allow for raid optimizations.

**Comment by PrincessRTFM** [comment]
I've updated the algorithm used for Verthunder/Veraero, those two will swap such that they won't equalise your mana levels now. For example, if your mana levels are equal and you cast Verthunder, using Veraero would equalise you again, so VT/VA will be VT on your bar.

As a result, you can get what you're looking for by putting VT/VA on your bar as well as VF/VS and using the long opener, then the combat button, then SC+A, then the long opener button _twice_. If you put, eg, Verthunder on `1` and Verfire on `2`, with Swiftcast and Acceleration on `3` and `4`, you'd want to do `1`, `2`, `3`, `4`, `1`, `1`.

This not only allows for raid optimisations (although admittedly you'll need to adjust to the sequence, but that's true with this plugin anyway) but also keeps the intelligent no-unbalancing feature of the combat opener button as before, so I hope it's a good compromise. The alternative was to add an option that would let you turn off the long opener swapping feature entirely, but then you'd be at risk of unbalancing.

Update will go live shortly.

**Comment by LaziestLou** [comment]
That's awesome, thank you so much?

**Comment by LaziestLou** [comment]
was meant to say thank you so much!*

(accidentally put question mark)
