### ISSUE TITLE
Summoner - Replace Slipstream with Swiftcast when Swiftcast is available

### ISSUE THREAD

**Issue by PrincessRTFM** [PrincessRTFM/XIVComboPlugin#18]
### Discussed in https://github.com/PrincessRTFM/XIVComboPlugin/discussions/17

<div type='discussions-op-text'>

<sup>Originally posted by **mikeff14** January 25, 2022</sup>
I wasn't sure where to suggest this and I don't know if this would be possible due to the way astral flow already changes into different skills, but this would be a really nice option! </div>

**Comment by PrincessRTFM** [comment]
@mikeff14 It might be possible, but Swiftcast and Slipstream do _totally_ different things, so I'm not sure why it would be desirable. Especially since, as you pointed out, Astral Flow already turns into so many different things to start with - adding another one that replaces one of those things but does something totally unrelated seems like it'd only cause confusion.

**Comment by mikeff14** [comment]
> 

Oh this might be personal preference but at least for me, optimizing dps on SMN involves swiftcasting slipstream on cd when Garuda comes out rather than using it for resses. So it would free up another keybind and make it faster to have the Astral Flow button become Swiftcast when it's time to cast Slipstream.

**Comment by PrincessRTFM** [comment]
I don't see why not, since it's a toggle option. Should have it working, although I don't play SMN so I can't test it myself. I'll push it now, lemme know if it's broken.

**Comment by mikeff14** [comment]
> I don't see why not, since it's a toggle option. Should have it working, although I don't play SMN so I can't test it myself. I'll push it now, lemme know if it's broken.

Works perfectly! Thank youuuuu
