### ISSUE TITLE
Possible Bug with Lunar AoE and Solar Aoe feature.

### ISSUE THREAD

**Issue by Spanglish1337** [PrincessRTFM/XIVComboPlugin#20]
Hi!

Thank you for doing the WAR change the other day, it helped me tremendously!

Today I wanted to mention a possible bug with the Lunar AoE feature and Solar AoE feture. I have been playing MNK a lot (favorite melee, I love it, thank you for helping me and others play it with your plugin) and when this settings are activated: 
![image](https://user-images.githubusercontent.com/89648547/154113187-ee1bd291-00a5-4961-9df6-81d491a578b1.png)
the features work correctly, the aoe looks for Solar Nadi and then Lunar Nadi. 

However, for some reason, when THIS is activated: 
![image](https://user-images.githubusercontent.com/89648547/154113351-be0a44f1-c9da-4f88-af96-94fe1d79d5be.png) (four point fury aoe feature) the aoe just keeps looking for Lunar, Luna, Lunar and Lunar again, and Solar very rarely. 

So sorry english not first language, if I did not explain anything correctly please let me know, thank you again for your plugin!

**Comment by PrincessRTFM** [comment]
I'm going through all of the existing combos to merge in things that daemitus's fork has that mine doesn't, so I'll look at this too. Unfortunately, I don't play (or even _have_) Monk, so I can't really test it. If the update (which I'll release when I'm done with everything) doesn't fix it, would you be available on discord to try test builds, if I walk you through loading them?

**Comment by Spanglish1337** [comment]
I don't have MNK maxed yet but if I can help, I am available on discord, that is correct. My discord is spanglish#1337

**Comment by PrincessRTFM** [comment]
Update: the code from Monk's combos is kicking my ass. Some features are probably being dropped for the next update until I figure out how to add them back in, which will require help from people who play Monk.

I swear this is the most complicated job to write replacers for.

**Comment by PrincessRTFM** [comment]
Unfortunately, the Lunar/Solar features were among those dropped in this update. The AoE combo has been completely revamped to apply to Masterful Blitz instead, thanks to a weird bug in the old version. Once this update (it's a _big_ one, I'm merging in upstream changes on _every_ job) is done, please open a new issue with _any and all_ combos and features that you want (re)added, in as much detail as possible. I promise I'll try to get everything I can.

**Comment by Spanglish1337** [comment]
Hi!

That is fine! I will check what features are missing in the new update, and taking an image of the current ones to remember which, because so far, just getting rid of Four Point Fury AoE Feature makes the class work like a legend.

**Comment by Evolutious** [comment]
Hello friend. It looks like whatever was done here really broke a ton of stuff now in the AOE (and even ST) stuff. Basically with you using Masterful Blitz as your AOE proxy spell, and as a MNK you use Masterful Blitz in all situations, not just AOE, you now have a situation where during a ST rotation, Masterful Blitz is changing into an AOE ability instead of firing off Masterful Blitz. Please reconsider using Masterful Blitz as the AOE proxy action so it does not goof with teh ST rotation.

**Comment by PrincessRTFM** [comment]
I should really pick up Monk at some point.

I'll take a look when I get the chance, I just got my computer working again after it being broken for a week.
