### ISSUE TITLE
Feature request for Paladin

### ISSUE THREAD

**Issue by BaexTower** [PrincessRTFM/XIVComboPlugin#21]
Can an option be added to have the end of Fast Blade -> Riot Blade -> Royal Authority (Rage of Halone), change to Goring Blade if the damage over time debuff has 7 seconds or less?

**Comment by PrincessRTFM** [comment]
Hang on, I might have an idea.

**Comment by PrincessRTFM** [comment]
Oh, derp. Yeah no, that's on me, I had the checks for "turn into GB" in the wrong place.
