### ISSUE TITLE
Monk needs to be overhauled

### ISSUE THREAD

**Issue by PrincessRTFM** [PrincessRTFM/XIVComboPlugin#24]
Masterful Blitz is not a good basis for combos, and a lot of stuff was lost in the last release.

**Comment by Spanglish1337** [comment]
Is there a way to see a list of what has been missing? I tried MNK in a dummy and so far the combos are working as intended

**Comment by PrincessRTFM** [comment]
According to #23, MB wasn't a good call for the combos, although they've since added that it's apparently not a big deal now. As for what's missing, probably a diff between versions of the `CustomComboPreset.cs` file? But, I'll be honest, I don't play Monk, I don't even _have_ it, and it's inexplicably a pain in the ass to write combos for, beyond even the other jobs I don't have. Something about it just crunches the gears in my head. So what I wound up doing (and have done a few times now) is just pull in the upstream changes from daemitus's fork.

For several unfortunate reasons, I can't really play XIV for some time, so the best I'll probably be able to do is take (clearly described) requests and try to implement them.

I'm very sorry for this, and once I have the chance to play again, I'll try and unlock Monk so I can better understand the way it works. For now, it sounds like this issue is cancelled, although feel free to open requests for features you'd like on Monk, and I'll do my best with them.

**Comment by Evolutious** [comment]
Hey there PrincessRTFM! I appreciate all that you have done with your mod so far both working with me on the MNK stuff and others. I will continue to provide you the same style of feedback with intended specific changes to the file that you can then polish if you prefer to do thing in a different manner but same results ;)

But as others have stated, everything seems to be working well currently. Take your time away from the game and I hope you are able to return soon!
