### ISSUE TITLE
Allow changing timeout on buff savers

### ISSUE THREAD

**Issue by Rigaln** [PrincessRTFM/XIVComboPlugin#25]
https://github.com/PrincessRTFM/XIVComboPlugin/issues/19
Is it possible to have the option to change the seconds of this to a different time?
Because with 7 seconds, I sometimes lose the buff.
I don't know which time is better, so it would be nice to be able to specify!

**Comment by Spanglish1337** [comment]
Oh I mentioned 7 seconds in my suggestion back then because in The Balance discord it was mentioned you should refresh the timer at 7 seconds or less because that is how a whole 1-2-3 combo would take from scratch. Personally I have not had this issue, but it may be if we have different GCD speeds?

**Comment by Rigaln** [comment]
I thought it would be nice to be able to set something other than 7 seconds, because I've seen the buffs update after 0 seconds.

**Comment by PrincessRTFM** [comment]
Definitely a reasonable request, but the config system isn't currently set up to make that easy. I'll look into it (and it's certainly possible!) but don't expect it right away, I'm afraid. I may have to redesign the config system, although if it comes to that I'm sure I can at least throw in a temporary hack similar to the dancer one to change what actions become dance steps...

Finally have my computer fixed and my dev environment back, so I'm earmarking this one to be done once there aren't any more (obvious) bugs.

**Comment by PrincessRTFM** [comment]
Good news, I've had an idea that should work pretty well, so expect this in a near-future update, assuming nothing goes horribly wrong with my computer again
