### ISSUE TITLE
Request to a fix for No Mercy - Bow Shock / Sonic Break , with a different priority

### ISSUE THREAD

**Issue by Spanglish1337** [PrincessRTFM/XIVComboPlugin#26]
![image](https://user-images.githubusercontent.com/89648547/157586376-ca3918af-495c-46b1-b603-cc1160fb7e25.png)

Hi. As the description mentions, No Mercy should turn into Bow Shock, and then Sonic Break.

Currently it is performing backwards, meaning the after No mercy, Sonic Break is showing first instead. If it is possible, It would be a good QoL, in my opinion at least, to have Bow Shock first as intended, as it would help with big pulls on dungeons, intead of having to cast Sonic Break first on a minion before Bow Shock, as it triggers a global cooldown.

**Comment by PrincessRTFM** [comment]
Oh, that's a bug. Lemme pull up the code and take a look at this...

**Comment by PrincessRTFM** [comment]
Yep, found it. Small oversight when I implemented that one.

**Comment by Spanglish1337** [comment]
Just tried and it works as intended, thank you so much <3
