### ISSUE TITLE
A suggestion for Warrior

### ISSUE THREAD

**Issue by Spanglish1337** [PrincessRTFM/XIVComboPlugin#27]
Hello, PrincessRTFM, hope everything is going well.

I would like to make a suggestion, if it is not complicated to do so.

If you have 80 beast gauge, and your next cast is Storm's Path, it will change to Fell Cleave. This is how it normally behaves, the issue is is if you are in 80 beast gauge, and your next cast is storm'spath/Storm's eye, even if you don't have the buff, it will change to Fell Cleave. 
![image](https://user-images.githubusercontent.com/89648547/158114990-965364c1-75bf-4b21-ba08-fa525070516b.png)

Is there a way to prioritize to apply Storm's Eye's buff before casting the Fell Cleave?

**Comment by PrincessRTFM** [comment]
Currently, there are three overrides before the simple Heavy Swing -> Main -> Storm's Path combo is used:
1. If you have enabled the Inner Release feature and have the Inner Release buff, become Fell Cleave.
2. If you have enabled the overcap saver and have >70 Beast Gauge, become Fell Cleave.
3. If you have enabled the smart storm feature and have <7 seconds left on Surging Tempest, follow the Storm's Eye chain.
4. If none of the above condition sets are met, follow the Storm's Path chain.

I can swap 2 and 3 easily, which is what you're asking for, but should I put 3 before 1 or leave that as it is? I've never played Warrior, so I don't know the best order for this to go in.

And I haven't forgotten the configuration detail update to change the time on the Surging Tempest buff, it's still coming!

**Comment by Spanglish1337** [comment]
Hello Princess.

Swapping 2 and 3 is more than enough as the regular opener of warrior is to do the first 3 chain combo for Storm's Eye buff and then activate Inner Release, so just switching 2 and 3 should be more than fine., in the case that there is not an overcap.

About changing the time, I was delving more in The Balance discord and they mention that the debuff can be refreshed between 7 and 15 seconds. Since the average of 7 and 15 should be 11, we could change it to that timer for the time being until the manual timer that you are working is implemented, in my opinion.

Thank you so much for your help! <3

**Comment by PrincessRTFM** [comment]
The buff time is now configurable actually, from the recent config system update. If you open the window, go the Warrior section, and enable the combos in question, you should get an input to select how much time you want to have left on the buff before it changes the combo chain.
