### ISSUE TITLE
Suggestions for additional functionality

### ISSUE THREAD

**Issue by Rigaln** [PrincessRTFM/XIVComboPlugin#30]
warrior
- Ability to add Tomahawk to Storms Path Combo if it's too far away to hit.
- Adding an option to Gauge Ovecap to be used as soon as it exceeds 50

**Comment by Spanglish1337** [comment]
If option 2 is added I would please request to be functional only if only you have the Storm's Eye buff up.

**Comment by Rigaln** [comment]
We would all be happy if as an option we could choose to use it as soon as we go over 50, or when we go over 100, or only if the Storm's Eye buff is up, or if the function is only available when the Storm's Eye buff is up.

**Comment by PrincessRTFM** [comment]
I'm not sure I like the first, because that's a totally separate action. It doesn't save you anything, and in fact it _loses_ you the combo; there's a keybind for "target nearest enemy" that would allow you to switch to something closer if you don't think you can catch up to the original target in time. But with this, being slightly out of range, even by accident, would cause your combo to end early. On top of that, it'd be pretty suspicious, since you'd be midway through a combo then suddenly use a ranged attack on an enemy that's a yalm or two further out. I think this is a kinda bad idea, honestly.

The gauge overcap feature is designed to give you as much choice as possible as to when to use the gauge spender, and only kicks in the override when you're about to "waste" gauge increases. If you want to use the gauge spender early, then just put the button on your hotbars and hit it when you want it. That one, I'm willing to see about implementing, but I still don't feel like it's a good idea, personally. Is it really better than the existing system?

**Comment by Spanglish1337** [comment]
> The gauge overcap feature is designed to give you as much choice as possible as to when to use the gauge spender, and only kicks in the override when you're about to "waste" gauge increases. If you want to use the gauge spender early, then just put the button on your hotbars and hit it when you want it. That one, I'm willing to see about implementing, but I still don't feel like it's a good idea, personally. Is it really better than the existing system?

I would not say it is better. The current system is fine as top WAR's save gauge and just spend when about to overcap and when raid buffs align to accommodate more damage.

IF any change would be needed, the only slightly improvement is to change how the over-capping works, meaning that if you have 80 beast gauge, and your next GCD is the 3rd combo that gains 20 of your bar, the current system changes to Fell Cleave and cast it, when in theory it should just cast the GCD, let the bar get to 100, and you can cast the Fell Cleave. 

At least, in theory, this is how it should behave. Also I am super picky about those things, sadly...

**Comment by Spanglish1337** [comment]
Also I would request if possible, to have Thrill of battle > Equilibrium on the same button, without being on top of Nascent Flash.

**Comment by PrincessRTFM** [comment]
So, the way it _currently_ works is that it checks if you've enabled the gauge saver, if your level is high enough to have the beast gauge unlocked, and if your gauge is _over_ 70. If that's _all_ true, it becomes Fell Cleave; if one or more of those conditions isn't met, it goes on to do the 1-2-3 combo.

It sounds like what's happening is you have less than 80 gauge, start your combo, and then partway through you get 80+ gauge, which turns it into Fell Cleave. That's an edge case I hadn't thought of before, but I should be able to fix that.

**Comment by PrincessRTFM** [comment]
Thrill of Battle and Equilibrium are on Bloodwhetting and Raw Intuition, Nascent Flash isn't part of that combo.

**Comment by Spanglish1337** [comment]
> Thrill of Battle and Equilibrium are on Bloodwhetting and Raw Intuition, Nascent Flash isn't part of that combo.

Oohh... Okay, I just got Bloodwhetting today so I have not tried the option again. Thank you!!

**Comment by Spanglish1337** [comment]
> So, the way it _currently_ works is that it checks if you've enabled the gauge saver, if your level is high enough to have the beast gauge unlocked, and if your gauge is _over_ 70. If that's _all_ true, it becomes Fell Cleave; if one or more of those conditions isn't met, it goes on to do the 1-2-3 combo.
> 
> It sounds like what's happening is you have less than 80 gauge, start your combo, and then partway through you get 80+ gauge, which turns it into Fell Cleave. That's an edge case I hadn't thought of before, but I should be able to fix that.

It changes when you get exactly 80. Like this:

![image](https://user-images.githubusercontent.com/89648547/159789611-09495b39-65d1-4b9f-ab86-2cda4d9b8471.png)

In the image above, the next action is Storm's Path, which will take me exactly to 80. 

![image](https://user-images.githubusercontent.com/89648547/159789706-3c91b1ca-c02a-4e9c-bd37-5334f43ecacc.png)

In this image, above, I have casted Storm's Path, and the gauge is exactly 80. The next GCD is Heavy Swing, which would not produce beast gauge, and the one after that, just gives 10 beast gauge, but it would still offer me Fell Cleave, instead. If I am explaining myself correctly.

**Comment by Spanglish1337** [comment]
> That's an edge case I hadn't thought of before, but I should be able to fix that.

Unless you mean like this that you are already checking it out... and I am just dumb, my apologies. Thank you so much for your work on this. 

Also, the bloodwhetting with the HP skills work amazing too, thank you.

**Comment by Spanglish1337** [comment]
> > So, the way it _currently_ works is that it checks if you've enabled the gauge saver, if your level is high enough to have the beast gauge unlocked, and if your gauge is _over_ 70. If that's _all_ true, it becomes Fell Cleave; if one or more of those conditions isn't met, it goes on to do the 1-2-3 combo.
> > It sounds like what's happening is you have less than 80 gauge, start your combo, and then partway through you get 80+ gauge, which turns it into Fell Cleave. That's an edge case I hadn't thought of before, but I should be able to fix that.
> 
> It changes when you get exactly 80. Like this:
> 
> ![image](https://user-images.githubusercontent.com/89648547/159789611-09495b39-65d1-4b9f-ab86-2cda4d9b8471.png)
> 
> In the image above, the next action is Storm's Path, which will take me exactly to 80.
> 
> ![image](https://user-images.githubusercontent.com/89648547/159789706-3c91b1ca-c02a-4e9c-bd37-5334f43ecacc.png)
> 
> In this image, above, I have casted Storm's Path, and the gauge is exactly 80. The next GCD is Heavy Swing, which would not produce beast gauge, and the one after that, just gives 10 beast gauge, but it would still offer me Fell Cleave, instead. If I am explaining myself correctly, as the AoE combo does offer the AoE spender as soon as the next GCD will over-cap it, and not before.

**Comment by Spanglish1337** [comment]
![image](https://user-images.githubusercontent.com/89648547/159849097-ed51dc05-7474-4e96-9671-af69b4b3aae4.png)

Question, can this option be for Bloodwhetting too, if possible? Since it is the main one Warriors use, and Nascent Flash just works with party members, just ourselves.

**Comment by Spanglish1337** [comment]
@PrincessRTFM Sorry for the double posting... I realized I suck at quoting stuff...

Wanted to just add "If I am explaining myself correctly, as the AoE combo does offer the AoE spender as soon as the next GCD will over-cap it, and not before. The change would make saving gauge better, at the last moment, to align for raid buffs."

**Comment by PrincessRTFM** [comment]
So, the way it's _designed_ right now (and was always intended) is that before you start your main 1-2-3 combo, if _completing the whole combo_ would overcap your gauge, it becomes Fell Cleave instead, so you don't halfway through a combo and then interrupt it with FC. That means that when you're not in your 1-2-3 combo (either of them) and you have 80+ gauge, it should change into FC.

If that's what it's doing, then it's working as intended; however, if there's a better way to implement this (like if it shouldn't pre-check the whole combo, for instance) then please [open a new issue](https://github.com/PrincessRTFM/XIVComboPlugin/issues/new) to let me know.

As a side note, please try to use a more descriptive title than "suggestions for additional functionality" if you can, for people searching issues in the future.
