### ISSUE TITLE
MNK - Feature Adjustment

### ISSUE THREAD

**Issue by Evolutious** [PrincessRTFM/XIVComboPlugin#31]
Good day - Looking at the Perfect Balance Feature; you have it so that it changes into Masterful Blitz when you have 3 Beast Chakras filled, but I wanted to see if you wouldn't mind adjusting this so that it changes into Masterful Blitz if you have the Perfect Balance buff as well. I cannot think of a single instance where it would be beneficial to be able to use Perfect Balance while you still have 1 or more charges of Perfect Balance buff still active.

You could also split this into its own feature if you wanted as well if you think that being able to use Perfect Balance while under an active Perfect Balance buff would be desired (again, I cannot think of a single instance where that would be true)

Change
~~~C#
if (level >= MNK.Levels.MasterfulBlitz && !GetJobGauge<MNKGauge>().BeastChakra.Contains(BeastChakra.NONE))
~~~

To
~~~C#
if (level >= MNK.Levels.MasterfulBlitz && (!GetJobGauge<MNKGauge>().BeastChakra.Contains(BeastChakra.NONE) || SelfHasEffect(MNK.Buffs.PerfectBalance))
~~~

**Comment by Spanglish1337** [comment]
If this prevents for Perfect Balance to be used twice if you spam the button, I agree it would be a great adjustment.

**Comment by Evolutious** [comment]
That would be exactly what it would result in.

**Comment by Evolutious** [comment]
Hi @PrincessRTFM - Thank you for making the adjustment, but it looks like you did it in the wrong place; I will explain below.

What you did was change (MonkAoECombo)
~~~C#
	internal class MonkAoECombo: CustomCombo {
		public override CustomComboPreset Preset { get; } = CustomComboPreset.MonkAoECombo;

		public override uint[] ActionIDs { get; } = new[] { MNK.MasterfulBlitz };

		protected override uint Invoke(uint actionID, uint lastComboMove, float comboTime, byte level) {
			MNKGauge gauge = GetJobGauge<MNKGauge>();

			// Blitz
			if (level >= MNK.Levels.MasterfulBlitz && !GetJobGauge<MNKGauge>().BeastChakra.Contains(BeastChakra.NONE))
				return OriginalHook(MNK.MasterfulBlitz);
~~~

into 
~~~C#
	internal class MonkAoECombo: CustomCombo {
		public override CustomComboPreset Preset { get; } = CustomComboPreset.MonkAoECombo;

		public override uint[] ActionIDs { get; } = new[] { MNK.MasterfulBlitz };

		protected override uint Invoke(uint actionID, uint lastComboMove, float comboTime, byte level) {
			MNKGauge gauge = GetJobGauge<MNKGauge>();

			// Blitz
			if (level >= MNK.Levels.MasterfulBlitz && (!GetJobGauge<MNKGauge>().BeastChakra.Contains(BeastChakra.NONE) || SelfHasEffect(MNK.Buffs.PerfectBalance)))
				return OriginalHook(MNK.MasterfulBlitz);
~~~

But what I was actually asking for was to change (MonkPerfectBalance)
~~~C#
	internal class MonkPerfectBalance: CustomCombo {
		public override CustomComboPreset Preset { get; } = CustomComboPreset.MonkPerfectBalanceFeature;
		public override uint[] ActionIDs => new[] { MNK.PerfectBalance };

		protected override uint Invoke(uint actionID, uint lastComboMove, float comboTime, byte level) {

			if (level >= MNK.Levels.MasterfulBlitz && !GetJobGauge<MNKGauge>().BeastChakra.Contains(BeastChakra.NONE))
				// Chakra actions
				return OriginalHook(MNK.MasterfulBlitz);
~~~

into
~~~C#
	internal class MonkPerfectBalance: CustomCombo {
		public override CustomComboPreset Preset { get; } = CustomComboPreset.MonkPerfectBalanceFeature;
		public override uint[] ActionIDs => new[] { MNK.PerfectBalance };

		protected override uint Invoke(uint actionID, uint lastComboMove, float comboTime, byte level) {

			if (level >= MNK.Levels.MasterfulBlitz && (!GetJobGauge<MNKGauge>().BeastChakra.Contains(BeastChakra.NONE) || SelfHasEffect(MNK.Buffs.PerfectBalance)))
				// Chakra actions
				return OriginalHook(MNK.MasterfulBlitz);
~~~

I do not think the change you made to MonkAoECombo will actually do anything as it was changed, since you are not actually using Perfect Balance in your MonkAoeCombo feature currently. I think if you can revert the change you made in the MonkAoECombo section and make the change to the MonkPerfectBalance section instead, this will be good to go.

Also, any chance you coudl update the feature text in the option panel to change it from ```Replace Perfect Balance with Masterful Blitz when you have 3 Beast Chakra.``` to ```Replace Perfect Balance with Masterful Blitz when you have 3 Beast Chakra or under the effects of Perfect Balance.```

**Comment by PrincessRTFM** [comment]
Oh whoops - lemme fix that.
