### ISSUE TITLE
WAR - Adjustment for "Angry Beast Feature" if possible

### ISSUE THREAD

**Issue by Spanglish1337** [PrincessRTFM/XIVComboPlugin#33]
Greetings.

If possible, is there a chance that we can make Infuriate change into Fell Cleave, when it is over 50? There are times where I would like to save beast-gauge, it is at 50, and you can cast Infuriate for a Inner-Chaos because either A) you are about to cap 2 Infuriate charges again or B) you want to Inner Chaos quick to force a crit heal in a Bloodwhetting, for a tank buster, for example. And instead, it casts fell-cleave.

Wondering if something like this is possible. Thank you! (And if I am explaining myself correctly.)

**Comment by PrincessRTFM** [comment]
Sorry for the delay, I've been setting up a whole new computer.

I'm not quite sure I understand, but it sounds like you want a feature to force Infuriate to become Fell Cleave whenever FC is usable? Would that apply to an existing combo, or only when Infuriate is placed on a hotbar?

**Comment by Spanglish1337** [comment]
Greetings, thank you for your response, building a new pc is very fun! At least for me. I'll explain my case as best as possible. 
The "Angry Beast feature" makes Fell Cleave change into Infuriate when you drag fell cleave into the action bar. 

In the next image, we have 0 beast gauge, so infuriate is still infuriate. 
![image](https://user-images.githubusercontent.com/89648547/161425146-0e323af5-bbdc-4eb4-b7f1-8c583f17e12f.png)

When you get 50 beast gauge, like in the next example, it changes into the spender (i.e. Fell Cleave / Inner Chaos)
![image](https://user-images.githubusercontent.com/89648547/161425224-8354bc72-14d5-40fb-85d5-ed3ad23c7574.png)

Would it be possible, to have a feature that makes it change to the spender, as soon as the beast gauge goes OVER 50 beast gauge instead of starting 50 beast gauge, as you can technically cast Infuriate without losing any beast gauge? It would get to 100, and then the spender would be cast after it. Like having a different "angry beast feature" that works like I mention, instead of the current one, as probably current warriors are used to it, but personally I want to save as much gauge as possible for when raid buffs allign.

**Comment by PrincessRTFM** [comment]
Ah! I think I understand now. Okay, for reference:

- the Angry Beast feature affects Inner Beast, Fell Cleave, Steel Cyclone, and Decimate
- it changes those actions into Infuriate only when _all_ of the following are true:
	- your level is greater than or equal to 50
	- your job gauge is _less_ than 50
	- you are not under the effect of Inner Release
- it is pre-empted by the Primal Beast feature, which will take effect (overriding Angry Beast) when _all_ of the following are true:
	- that feature is enabled
	- your level is at least 90
	- you have the effect Primal Rend Ready

What you're looking for is a subfeature to change the threshold from "job gauge less than 50, be Infuriate" into "job gauge less than _60_, be Infuriate", by the sound of things.

I'll implement that now, if I'm wrong then just let me know here and I'll fix it.
