### ISSUE TITLE
MNK - Perfect Balance Feature (Revisit)

### ISSUE THREAD

**Issue by Evolutious** [PrincessRTFM/XIVComboPlugin#34]
Hi @PrincessRTFM - I am not certain when I add a reply to a closed ticket, if you see that comment; so I am opening a new ticket with the comment I gave in the other ticket. Let me know if you get notified when someone replies to a closed ticket and I will not create a new ticket in the future (sorry if that is the case!)

Thank you for making the adjustment, but it looks like you did it in the wrong place; I will explain below.

What you did was change (MonkAoECombo)
~~~C#
	internal class MonkAoECombo: CustomCombo {
		public override CustomComboPreset Preset { get; } = CustomComboPreset.MonkAoECombo;

		public override uint[] ActionIDs { get; } = new[] { MNK.MasterfulBlitz };

		protected override uint Invoke(uint actionID, uint lastComboMove, float comboTime, byte level) {
			MNKGauge gauge = GetJobGauge<MNKGauge>();

			// Blitz
			if (level >= MNK.Levels.MasterfulBlitz && !GetJobGauge<MNKGauge>().BeastChakra.Contains(BeastChakra.NONE))
				return OriginalHook(MNK.MasterfulBlitz);
~~~

into 
~~~C#
	internal class MonkAoECombo: CustomCombo {
		public override CustomComboPreset Preset { get; } = CustomComboPreset.MonkAoECombo;

		public override uint[] ActionIDs { get; } = new[] { MNK.MasterfulBlitz };

		protected override uint Invoke(uint actionID, uint lastComboMove, float comboTime, byte level) {
			MNKGauge gauge = GetJobGauge<MNKGauge>();

			// Blitz
			if (level >= MNK.Levels.MasterfulBlitz && (!GetJobGauge<MNKGauge>().BeastChakra.Contains(BeastChakra.NONE) || SelfHasEffect(MNK.Buffs.PerfectBalance)))
				return OriginalHook(MNK.MasterfulBlitz);
~~~

But what I was actually asking for was to change (MonkPerfectBalance)
~~~C#
	internal class MonkPerfectBalance: CustomCombo {
		public override CustomComboPreset Preset { get; } = CustomComboPreset.MonkPerfectBalanceFeature;
		public override uint[] ActionIDs => new[] { MNK.PerfectBalance };

		protected override uint Invoke(uint actionID, uint lastComboMove, float comboTime, byte level) {

			if (level >= MNK.Levels.MasterfulBlitz && !GetJobGauge<MNKGauge>().BeastChakra.Contains(BeastChakra.NONE))
				// Chakra actions
				return OriginalHook(MNK.MasterfulBlitz);
~~~

into
~~~C#
	internal class MonkPerfectBalance: CustomCombo {
		public override CustomComboPreset Preset { get; } = CustomComboPreset.MonkPerfectBalanceFeature;
		public override uint[] ActionIDs => new[] { MNK.PerfectBalance };

		protected override uint Invoke(uint actionID, uint lastComboMove, float comboTime, byte level) {

			if (level >= MNK.Levels.MasterfulBlitz && (!GetJobGauge<MNKGauge>().BeastChakra.Contains(BeastChakra.NONE) || SelfHasEffect(MNK.Buffs.PerfectBalance)))
				// Chakra actions
				return OriginalHook(MNK.MasterfulBlitz);
~~~

I do not think the change you made to MonkAoECombo will actually do anything as it was changed, since you are not actually using Perfect Balance in your MonkAoeCombo feature currently. I think if you can revert the change you made in the MonkAoECombo section and make the change to the MonkPerfectBalance section instead, this will be good to go.

Also, any chance you coudl update the feature text in the option panel to change it from ```Replace Perfect Balance with Masterful Blitz when you have 3 Beast Chakra.``` to ```Replace Perfect Balance with Masterful Blitz when you have 3 Beast Chakra or under the effects of Perfect Balance.```

_Originally posted by @Evolutious in https://github.com/PrincessRTFM/XIVComboPlugin/issues/31#issuecomment-1086909592_

**Comment by PrincessRTFM** [comment]
All good, and for reference, yes I see comments on "closed" issues. Any discussion on any issues on this repo will send me a notification, regardless of whether the issue is open or not.
