### ISSUE TITLE
6.1 Patch

### ISSUE THREAD

**Issue by Evolutious** [PrincessRTFM/XIVComboPlugin#38]
Hello there! Just wanted to let you know that it looks like patch 6.1 broke your mod. It is failing to load while other forks (such as XIVCombo by attick) works but is missing a bunch of stuff that yours has.

It installs, but nothing works. /pcombo does not work, /pcombovx does not do anything, none of the previously selected features are working... not sure if you have any way to check this since you have said you are not playing currently. :'(

Help us @PrincessRTFM, you're our only hope!

**Comment by Spanglish1337** [comment]
I can confirm the plugin developers are updating their plugins with an API 6 of some sort

**Comment by PrincessRTFM** [comment]
Patch 6.1 broke all plugins, and Dalamud was only just released on stable. Other plugins use the testing fork to update, but since it's not stable, I don't. I'm updating now.

**Comment by Spanglish1337** [comment]
> Patch 6.1 broke all plugins, and Dalamud was only just released on stable. Other plugins use the testing fork to update, but since it's not stable, I don't. I'm updating now.

Aaah, okay! That makes sense. Will keep that in mind for next update. Thank you!

**Comment by Evolutious** [comment]
Thank you! :D

Sorry to ping you early as well, I have access to the beta versions of Dalamud so I get ahead of the official release and can see things like this sooner. hehe
