### ISSUE TITLE
PLD Atonement feature

### ISSUE THREAD

**Issue by username4447** [PrincessRTFM/XIVComboPlugin#46]
Hello, my atonement doesn't appear where my two other combos are (see screenshot)
[https://i.ibb.co/X8yBMXT/yeye.png](url)

**Comment by PrincessRTFM** [comment]
That feature only replaces the combos with Atonement when you're not in a combo at all, which is an oversight. It should apply when you're not in the combo being replaced. I'll get that fixed shortly.

**Comment by PrincessRTFM** [comment]
Fixed in 3ebde9e
