### ISSUE TITLE
PLD - 134 137 and 141 combos

### ISSUE THREAD

**Issue by username4447** [PrincessRTFM/XIVComboPlugin#47]
Hello, both royal authority and goring blade combos ends at riot blade then goes back to fast blade
If I check 134: goring blade (GB) combo, 137: royal authority (RA) combo and 141: atonement feature I can't use GB RA and atonement at all
If I check only 134, can't use GB
If I check only 137 can't use RA
If I check 141 with any 134/137 checked too, I wont see atonement since I don't see GB nor RA
If i check only 141, atonement doesn't replace RA

**Comment by PrincessRTFM** [comment]
I'm restructuring the logic used in those combos now, it should work shortly. If not, please reopen this issue to let me know, with whatever details you can give.
