### ISSUE TITLE
Monk AOE combo and WAR Single target combo

### ISSUE THREAD

**Issue by Theletha** [PrincessRTFM/XIVComboPlugin#57]
Hi

Im playing a 61 Monk atm and the aoe combo does not include the "Howling Fist" while the single target combo does include its counterpart "Steel Peak".
Is it a reason for this or am i too low lvl somehow? 

For WAR im wondering why upheaval isn't part of the single target combo?

**Comment by PrincessRTFM** [comment]
I play neither of those jobs, so it may just be that they were overlooked. For WAR specifically, they weren't part of the actual combo series, but it should be reasonable enough to add them. MNK eternally confounds and irritates me whenever I try to write combos for it, and I believe the current combo implementations were actually contributed by someone else, so I have no idea where they should fit into things.

If you can give me the specific prioritised conditions (integrated into the current setup, as in "if the combo doesn't become X, check these conditions for becoming HF/SP before trying to become Y") then I can probably add it, but like I said, I don't play Monk, so I have no context or experience to rely on for figuring it out myself.

**Comment by Theletha** [comment]
Maybe you can see how it looks in your code for the single target combo for when it uses "Steel Peak" or "The forbidden chakra" which it its upgraded version you get at lvl 54. 

The AOE combo should use "Howling fist" or "Enlightenment" (Enlight. replaces howling fist at 74) as soon as its available but only when GCD is active since the action is not on the GCD.

**Comment by Valmere** [comment]
For warriors Upheaval (single target) and Orogeny (aoe) are oGCD and can be used whenever, sliding them into the combo chains would be appreciated.

**Comment by PrincessRTFM** [comment]
Sorry for the wait, life got a little busy. oGCDs can easily be shoved into a weave assist feature, there's already a few elsewhere so that's easy enough to do. Just need to figure out the enable conditions for all of them.
