### ISSUE TITLE
NIN - Multiple combo features broken

### ISSUE THREAD

**Issue by howlingc** [PrincessRTFM/XIVComboPlugin#59]
Since the update multiple ninja combo action features are broken.

- Huraijin Feature (3024): Works only out of combat
- Huton Feature (3014): Does not work
- Single Target Smart Weave (3026): Does not work
- AoE Smart Weave (3027): Does not work

**Comment by PrincessRTFM** [comment]
Unfortunately, the last game patch changed some things in NIN's job gauge, and the library that dalamud (and therefore this plugin) uses to read job gauge data hasn't yet been updated to handle it.

**Comment by PrincessRTFM** [comment]
Correction: it was apparently updated about an hour ago (seven hours after this issue was opened) so it should, hopefully, be working once you relaunch your game and dalamud updates itself.

**Comment by howlingc** [comment]
Tested these out with the new dalamud version, and they work again.
