### ISSUE TITLE
MNK - AoE combo blocks usage of second Perfect Balance charge

### ISSUE THREAD

**Issue by Braggardt** [PrincessRTFM/XIVComboPlugin#60]
As of the latest release, the second charge of Perfect Balance cannot be activated if Monk AoE Combo (2000) is enabled. This occurs regardless of whether any the AoE combo's variations (On Destroyer (2099), On Masterful Blitz (2098) On Rockbreaker (2097)) are enabled.

**Comment by PrincessRTFM** [comment]
I _might_ have fixed it, not entirely certain. I think I had the new weave assist code in the wrong place. Let me know if the new version works.

**Comment by Braggardt** [comment]
That seems to have fixed it! Thanks for the quick response!
