### ISSUE TITLE
[GNB] Gnashing Fang replaced with Blood Fest when on the former is on cooldown and No Mercy is active

### ISSUE THREAD

**Issue by Tenrys** [PrincessRTFM/XIVComboPlugin#65]
This happens with no action replacements enabled, and gets in the way a little. Is there a way to fix this?

**Comment by Tenrys** [comment]
https://github.com/PrincessRTFM/XIVComboPlugin/blob/master/XIVComboVX/Combos/GNB.cs#L330

This seems to be the culprit. Shouldn't there be a toggle for it? Is this even how it should work? Because it seems like it stops you from continuing the Gnashing Fang combo.

**Comment by PrincessRTFM** [comment]
Yyyyep. We must've missed that, sorry. Gimme a few and I can have a fix up.
