### ISSUE TITLE
Paradin's "Confiteor feature" does not lead to Blade of Faith Combo

### ISSUE THREAD

**Issue by inu-goro** [PrincessRTFM/XIVComboPlugin#66]
I was using "Confiteor feature" (debug#1908), and Holy spirit changes to Confiteor all right, but it does not lead to the Blade of Faith combo.

(I have a feeling it was working a while ago although I am not absolutely sure.
I'm sorry if it wasn't supposed to work that way in the first place.)

I tooked screenshots to compare it with Requiescat Feature (debug#1905):

I placed Holy Spirit to the left side and Royal Authority (replaced with Fast Blade) on the right
![original](https://user-images.githubusercontent.com/113815605/190886268-717aa452-1aa1-459e-a010-a6c13a7fbf47.png)

and started requiescut.
![holy spirit](https://user-images.githubusercontent.com/113815605/190886276-0023ab49-e2f9-4b7c-8021-09d6c1641ff7.png)

then Confiteor, both are working alright.
![confi](https://user-images.githubusercontent.com/113815605/190886294-6ff145c2-a419-474f-9452-251019cd6807.png)

After confiteor, Royal Authority is replaced with Blade of Faith, but Holy Spirit is unchanged.
![bov](https://user-images.githubusercontent.com/113815605/190886300-aee060c4-24db-4ecf-b550-b71df8b16afa.png)

Other enabled feature: royal authority combo (debug#1901) + dot saver(debug#1909)

I'd be glad if there was a way to fix this.

**Comment by PrincessRTFM** [comment]
Hm, github didn't recognise that as closing the issue. Well, it did.

For reference, you'll need to active the _new_ child combo under the Confiteor feature, in order to make this happen.

**Comment by inu-goro** [comment]
Thank you it now works perfect! Sorry to bother you so late at night.

**Comment by PrincessRTFM** [comment]
Time isn't real, don't worry about it.

On a more serious note, you just left a report pinned to the board, I'm the one who checked it :P
