### ISSUE TITLE
[GNB] Burst Strike into Double Down feature improvement

### ISSUE THREAD

**Issue by bronzo44** [PrincessRTFM/XIVComboPlugin#67]
Hello,
let me start with saying that I love this feature, it's the only thing I use XIVCombo for and I find it amazing, making me save a very needed keybind and at the same time making the BS/DD key feel so... Nice and powerful!

That said, there is one pretty big issue with this: using this feature forces you to drift DD by 1 GCD every minute: this happens because DD's cooldown comes off together with the GCD timer, hence the key is a Burst Strike all the way until the GCD ends, and only after that it becomes DD. So, if you spam the key, you might fire off a Burst Strike (it's not totally consistent, it seems it might be latency related? But it is a risk), even if in that GCD DD is already up.

Currently having a separate keybind for DD to use just occasionally, since you can afford with 2.42 or even 2.45 sets to drift almost all DDs and then reverse drift it with a couple off-CD usages, seems to be the best course of action.

Now, that solution kills the purpose of this feature. Moreover, the 2.50 set that's been recently proposed and that looks like it could be actually strong in a few fights this tier totally negates the possibility of drifting DD, since the reverse drift cannot happen at 2.50 - which means, if you drift it, you drift it for good and eventually it'll slip out of NM.

What I think could be a reasonable solution is to change how the BS-DD key substitution works, making it so the swap happens 1 or 2 seconds before DD comes off CD. This would allow players to have DD on the key before the GCD finishes rolling, and fire it off CD... And also have a nice viasual clue of DD coming off CD without another dedicated keybind.

This is possible because there is no scenario in which, during NM, you want to fire off a stray BS when DD is about to be ready.

If that doesn't sound fair enough, it could even be a sub-feature of the normal BS into DD a 2sec pre-key swap so the users might decide what's more interesting for them.

Sorry for the textwall, I wanted to be as precise as possible with this request. Thank you for your attention!

**Comment by PrincessRTFM** [comment]
I'm going to ping @damolitionn for this one, since they did practically all of the work on that feature, and also because I don't have GNB. Hopefully they'll be able to help.

**Comment by bronzo44** [comment]
I tried it and it's just amazing, it's perfect this way! I just cannot thank you enough for it and for having been so fast! Thanks!
