### ISSUE TITLE
CooldownTotal seems to only return value when targeted actionID is on cooldown

### ISSUE THREAD

**Issue by vitharr137** [PrincessRTFM/XIVComboPlugin#69]
In attempting to calculate how many GCDs remained until an action was off cooldown, I tried this variable for MNK: 

var gcd = GetCooldown(MNK.Bootshine).CooldownTotal;
var rofcd = GetCooldown(MNK.RiddleOfFire).CooldownRemaining;
var firegcds = IsOnCooldown(MNK.RiddleOfFire) ? rofcd / gcd : 0;

However, in testing, it, the action modification only returned while the GCD for Bootshine was cycling, and was ineffective when not pressing anything. Once I changed the variables to the following, it worked as expected:

var gcd = 1.94f;
var rofcd = GetCooldown(MNK.RiddleOfFire).CooldownRemaining;
var firegcds = IsOnCooldown(MNK.RiddleOfFire) ? rofcd / gcd : 0;

I am unsure if this is intended or not, but it is possible the code returning 0 in the CooldownTotal definition may be the cause

**Comment by PrincessRTFM** [comment]
That was only slightly refactored but otherwise taken untouched from the original fork. I can't speak to whether it was intended behaviour on there, but it wasn't necessary here. Good catch!

**Comment by vitharr137** [comment]
Thank you for addressing this so quickly! Unfortunately, it seems the same result occurs. For simple testing, this code specifically seems to to result in the behavior:
```
float gcd = GetCooldown(MNK.Bootshine).CooldownTotal;
float rotate = gcd * 3;
if (SelfHasEffect(MNK.Buffs.RaptorForm)) {
  if (level < MNK.Levels.TrueStrike) {
    return MNK.Bootshine;
  }
  
  return level < MNK.Levels.TwinSnakes || SelfEffectDuration(MNK.Buffs.DisciplinedFist) >= rotate
    ? MNK.TrueStrike
    : MNK.TwinSnakes;
}
```

What occurs exactly is the button will display properly until the last moment when Bootshine completes its cooldown, thus causing True Strike to cast instead of the properly shown Twin Snakes, as before, setting the gcd float to this causes the combo button to act as expected
```float gcd = 1.94f;```

Otherwise, no issues have been found with the updated CooldownTotal

**Comment by vitharr137** [comment]
Gotcha, hope I got this right. Learned how to make a fork/branch so you could also see the code changes I'm working on. Still learning the grammar of your repo so I can match my hackjob of code more closely [https://github.com/vitharr137/XIVComboPlugin](url) but if this can work I'll continue publishing to there if I get something useful going

I am seeing "Custom Combo Setup - XIVComboVX v7.0.8314.19446, debug build" at the top of the settings screen on my modified version, only my custom MonkUltimaCD selection is enabled, and here are the two dalamud.log samples I took under those instructions:

[dalamud bootshine button press specifically.log](https://github.com/PrincessRTFM/XIVComboPlugin/files/9727557/dalamud.bootshine.button.press.specifically.log)
I targeted Masterful Blitz as the button for MonkUltimaCD, so this log was taken when pressing specifically the Bootshine button, captured prior to pressing, and stopped capturing while the cooldown was cycling

[dalamud masterful blitz combo button clicked until bootshine appeared.log](https://github.com/PrincessRTFM/XIVComboPlugin/files/9727560/dalamud.masterful.blitz.combo.button.clicked.until.bootshine.appeared.log)
This log snippet directly followed, this is beginning the capture, pressing the Masterful Blitz combo button until Bootshine appeared in the rotation, then stopping capture after it was pressed and the cooldown was cycling.

Additional DLL hooks involved are GShade and XIVAlexander, just in case that is important

In both logs I am seeing there be an issue if I read your custom debug message right:
```
2022-10-06 11:18:38.965 -07:00 [INF] [XIVComboVX] Retrieved cooldown data for action #53: off cd, no charges, 0/0[0] (0)
2022-10-06 11:18:38.965 -07:00 [INF] [XIVComboVX] Retrieved cooldown data for action #7395: off cd, no charges, 0/0[0] (0)
```

compared to:

```
2022-10-06 11:18:42.249 -07:00 [INF] [XIVComboVX] Retrieved cooldown data for action #53: on cd, no charges, 1.528221/1.94[1.94] (0.41177905)
2022-10-06 11:18:42.249 -07:00 [INF] [XIVComboVX] Retrieved cooldown data for action #7395: off cd, no charges, 0/0[0] (0)
```

**Comment by vitharr137** [comment]
Sadness, but thank you so much for trying! That makes sense, it looks like manual calculation with [FFXIVClientStructs.FFXIV.Client.Game.UI PlayerState Attributes](https://goatcorp.github.io/Dalamud/api/FFXIVClientStructs.FFXIV.Client.Game.UI.PlayerState.html#FFXIVClientStructs_FFXIV_Client_Game_UI_PlayerState_Attributes) is my next search. I'll try to figure out a way to get those stats from the array and from there I can calculate the GCD, but if you're still willing to indulge me and find a way to import those stats like Skill Speed and Spell Speed, I'll be watching the repo!

```
Attributes : int {
    Strength = 1,
    Dexterity = 2,
    Vitality = 3,
    Intelligence = 4,
    Mind = 5,
    Piety = 6,
    MaxHp = 7,
    MaxMp = 8,
    CurrentMp = 10,
    CurrentGp = 11,
    Tenacity = 19,
    AttackPower = 20,
    Defense = 21,
    DirectHit = 22,
    MagicDefense = 24,
    CriticalHit = 27,
    AttackMagicPotency = 33,
    HealingMagicPotency = 34,
    Determination = 44,
    SkillSpeed = 45,
    SpellSpeed = 46,
    Craftsmanship = 70,
    Control = 71,
    Gathering = 72,
    Perception = 73
}
```
