### ISSUE TITLE
Engament in smartcast does not work if Leave one charge unselected

### ISSUE THREAD

**Issue by howlingc** [PrincessRTFM/XIVComboPlugin#74]
Engagement weaving in the smartcast feature does not work if "Leave one charge" (RedMageSmartcastSingleWeaveMeleeHoldOne#3531) feature is not also selected.

**Comment by PrincessRTFM** [comment]
Found the problem, my bad. I was using an XOR when I should've had an OR instead. Patch 6.3 is about to hit, so I'll push this fix along with the dalamud update, but that'll mean it won't work until after 6.3, so for today it's still broken. Sorry about that, but I just made the patch 6.3 update :/

Watch this space, the issue will auto-close when I actually release the patch 6.3 update.

**Comment by PrincessRTFM** [comment]
...how did you get a debug build, anyway? Did you build from source?

**Comment by PrincessRTFM** [comment]
Well, if you already have the source, you can go to `Combos/RDM.cs`, find `RedmageSmartcastSingleComboFull`, look at the `noCastingSubCheck` function, go to the definition of `bool shouldEngage` around like 393, and change `(!holdOneEngageCharge ^ engageCharges > 1)` to use `||` in place of `^`, then rebuild. But you don't need to build from source, all pushed commits that modify the source automatically build and deploy to my repo, so if you're using that then you can just update plugins from dalamud.
