### ISSUE TITLE
Potential Recast Time Fix

### ISSUE THREAD

**Issue by vitharr137** [PrincessRTFM/XIVComboPlugin#75]
Hello! 

Nothing vital, just a work in progress feature request. Given the base implementation of CooldownTotal is flawed from the original repo and returns 0 when nothing is on cooldown, I've been on the hunt for ways to improve it and I've located these two leads:

[GetRecastTime(ActionType, UInt32)](https://goatcorp.github.io/Dalamud/api/FFXIVClientStructs.FFXIV.Client.Game.ActionManager.html#FFXIVClientStructs_FFXIV_Client_Game_ActionManager_GetRecastTime_FFXIVClientStructs_FFXIV_Client_Game_ActionType_System_UInt32_)

[GetAdjustedRecastTime(ActionType, UInt32, Byte)](https://goatcorp.github.io/Dalamud/api/FFXIVClientStructs.FFXIV.Client.Game.ActionManager.html#FFXIVClientStructs_FFXIV_Client_Game_ActionManager_GetAdjustedRecastTime_FFXIVClientStructs_FFXIV_Client_Game_ActionType_System_UInt32_System_Byte_)

I'm trying to learn/test how to implement them myself but I admit I'm out of my depth. The main issue I'm attempting to solve is a better form of buff/debuff timer than raw seconds as for example Monk needs to reapply TwinSnakes/Demolish every 3 recasts, or 4 recasts if it's a Blitz rotation window. Having the ability to track the recast of Bootshine to apply that dynamically across levels and stats would greatly benefit that. Implementing either (if they are what I think they are) as some sort of GetRecast would unlock that ability

Thank you!

**Comment by PrincessRTFM** [comment]
> Given the base implementation of CooldownTotal is flawed from the original repo and returns 0 when nothing is on cooldown

When it's not on cooldown, the total _active_ cooldown time is zero, so that should be intended behaviour. If you're trying to get what the cooldown time _will be_ once the action is used, that's different, and might be somewhere in lumina.

But I don't know if being able to get the information you're talking about (AFAIU) would actually help you, since you said that

> Monk needs to reapply TwinSnakes/Demolish every 3 recasts, or 4 recasts if it's a Blitz rotation window

which means that you'd need to somehow decide between three or four recasts.

Can you give me some more details on what you're looking for and what you want to use it for? Maybe I can help, or at least point you in some possibly useful directions.

**Comment by vitharr137** [comment]
For sure, and it's mostly a work in progress on my side as well. I've used a bunch of math to get the recast timer for Monk and doing that let me calculate duration based off each recast instead of a raw number like 6 or 7 seconds. Below is an overview of what I use the code for, but the main feature request would be a way to track the simple GCD so I can use it later in code without having to setup the calculations per class. So far for what I've applied it to, tracking GCDs rather than stating reapply a buff/debuff at X seconds has been much more smooth and workable long term. I can share full code if you'd like as well

Recast Calculation example:
This class just tracks the current stat of Skill Speed and is needed before the other classes as a reference
```
public unsafe class MNKGCD
{
    public static unsafe int MNKSkillSpeed()
    {
        UIState* uiState = UIState.Instance();
        return uiState->PlayerState.Attributes[45];
    }
}
```

This section of code is all for calculating the Recast time of just Bootshine and outputting the float GCD to use later
```
int[,] levelSubAndDiv = new int[,] {
    { 56, 56 }, { 57, 57 }, { 60, 60 }, { 62, 62 }, { 65, 65 }, { 68, 68 }, { 70, 70 }, { 73, 73 }, { 76, 76 }, { 78, 78 },
    { 82, 82 }, { 85, 85 }, { 89, 89 }, { 93, 93 }, { 96, 96 }, { 100, 100 }, { 104, 104 }, { 109, 109 }, { 113, 113 }, { 116, 116 },
    { 122, 122 }, { 127, 127 }, { 133, 133 }, { 138, 138 }, { 144, 144 }, { 150, 150 }, { 155, 155 }, { 162, 162 }, { 168, 168 }, { 173, 173 },
    { 181, 181 }, { 188, 188 }, { 194, 194 }, { 202, 202 }, { 209, 209 }, { 215, 215 }, { 223, 223 }, { 229, 229 }, { 236, 236 }, { 244, 244 },
    { 253, 253 }, { 263, 263 }, { 272, 272 }, { 283, 283 }, { 292, 292 }, { 302, 302 }, { 311, 311 }, { 322, 322 }, { 331, 331 }, { 341, 341 },
    { 342, 366 }, { 344, 392 }, { 345, 418 }, { 346, 444 }, { 347, 470 }, { 349, 496 }, { 350, 522 }, { 351, 548 }, { 352, 574 }, { 354, 600 },
    { 355, 630 }, { 356, 660 }, { 357, 690 }, { 358, 720 }, { 359, 750 }, { 360, 780 }, { 361, 810 }, { 362, 840 }, { 363, 870 }, { 364, 900 },
    { 365, 940 }, { 366, 980 }, { 367, 1020 }, { 368, 1060 }, { 370, 1100 }, { 372, 1140 }, { 374, 1180 }, { 376, 1220 }, { 378, 1260 }, { 380, 1300 },
    { 382, 1360 }, { 384, 1420 }, { 386, 1480 }, { 388, 1540 }, { 390, 1600 }, { 392, 1660 }, { 394, 1720 }, { 396, 1780 }, { 398, 1840 }, { 400, 1900 }
};
float greasedLightningModifier;
if (level < 20)
    greasedLightningModifier = 0.95f;
else if (level < 40)
    greasedLightningModifier = 0.90f;
else if (level < 76)
    greasedLightningModifier = 0.85f;
else
    greasedLightningModifier = 0.80f;
int skillSpeed = MNKGCD.MNKSkillSpeed();
int baseBootshineCD = 2500;
float gcd = (baseBootshineCD * greasedLightningModifier * (1000 + (130 * (levelSubAndDiv[level - 1, 0] - skillSpeed) / levelSubAndDiv[level - 1, 1])) / 10000 / 100);
```

Then I can simplify the time to re-up something like Demolish into this specifically, as it takes 3 recasts to get to the next opportunity to use Demolish
```
float rotate = gcd * 3;
```

```
if (!HasEffect(MNK.Buffs.FormlessFist) && HasEffect(MNK.Buffs.CoerlForm))
{
    if (level < MNK.Levels.SnapPunch)
    {
        return MNK.Bootshine;
    }

    if (
        level >= MNK.Levels.Demolish
        && (demolish is null || demolish.RemainingTime < rotate))
    {
        return MNK.Demolish;
    }

    return MNK.SnapPunch;
}
```

It also means I can use the Recast time earlier and easier in checks like these for tracking if Demolish should be re-applied before a coming Blitz window:
This code tracks the GCDs left until Riddle of Fire
```
float rofcd = GetCooldown(MNK.RiddleOfFire).CooldownRemaining;
float firegcds = IsOnCooldown(MNK.RiddleOfFire) ? rofcd / gcd : 0;

```
This tracks the GCDs remaining in the Perfect Balance window
```
float perfectBalanceUpkeep;
if (beast3 != BeastChakra.NONE)
    perfectBalanceUpkeep = GetCooldown(MNK.Bootshine).CooldownRemaining;
else if (beast2 != BeastChakra.NONE)
    perfectBalanceUpkeep = GetCooldown(MNK.Bootshine).CooldownRemaining + gcd;
else if (beast1 != BeastChakra.NONE)
    perfectBalanceUpkeep = GetCooldown(MNK.Bootshine).CooldownRemaining + (gcd * 2);
else
    perfectBalanceUpkeep = gcd * 3;
```

This tracks how many GCDs occur between the different Nadi types of Blitzs
```
float demolishLunar = gcd * 8;
float demolishSolar = gcd * 2;
```

And putting those pieces together lets me track something like if Demolish needs to be refreshed going into a Riddle of Fire window depending on the state of the Beast Nadi
```
if (
    level >= MNK.Levels.Demolish
    && HasEffect(MNK.Buffs.CoerlForm)
    && !HasEffect(MNK.Buffs.PerfectBalance)
    && ((gauge.Nadi.HasFlag(Nadi.SOLAR)
        && ((level >= MNK.Levels.RiddleOfFire && firegcds <= 3) || (level < MNK.Levels.RiddleOfFire && GetCooldown(MNK.PerfectBalance).ChargeCooldownRemaining <= rotate))
        && (demolish is null || demolish.RemainingTime < demolishLunar))
        || (!gauge.Nadi.HasFlag(Nadi.SOLAR) && (demolish is null || demolish.RemainingTime < demolishSolar))))
{
    return MNK.Demolish;
}
```

**Comment by PrincessRTFM** [comment]
This is one of the reasons I hate MNK, not gonna lie. It seems so much more complicated than basically every other job.

I can't claim to fully understand half of this since I've never even glanced at playing it, and I'll admit I'm not.. crazy about hardcoding all of that skillspeed stat data, but this _does_ seem like a cool idea. Very advanced degree of player aid, but I kinda opened that door myself with smart weave combos.

Feel free to keep refining it, and if you get it to a release-viable state then open a PR (please use the included editorconfig for code style compatibility, and feel free to sign your work in a source comment) for inclusion. Monk is probably one of the most fragile jobs in this plugin since I don't know jack about it, and since I don't plan to pick it up, I wouldn't mind having someone else handle that.

**Comment by vitharr137** [comment]
I won't lie it has taken me a considerable amount of time to even get this far and I've reached the ends of my sanity a few times on it rofl. I think the discussion @Evolutious opened up has really cleaned up a lot of the code we're using into an actionable GCD call method, but I will gladly setup a PR once I translate all of what I have into your style!

**Comment by PrincessRTFM** [comment]
I honestly don't know, because those are in ClientStructs which is a way of labelling and calling the game's own functions - but I can't tell what those functions _do_. Good luck if you keep digging, though!

**Comment by vitharr137** [comment]
I believe this is the function that we're looking for, and the confusion I was having was it was returning an int, but it was returning the milliseconds. For example:

```
using FFXIVClientStructs.FFXIV.Client.Game;
```

```
int gcd2 = ActionManager.GetAdjustedRecastTime(ActionType.Spell, MNK.Bootshine);
```

This returns the number 1949, which equates to my current millisecond cool down of Bootshine, which is 1.94s (technically with a discrepancy of 1 millisecond, according to my calculations, it should be 1948, but the milliseconds get truncated with a floor function regardless)

I believe we have our dynamic answer, @Evolutious and I'll continue testing to see how it holds up/dynamically calculates, but this seems like the winner

**Comment by PrincessRTFM** [comment]
Nice work! If you and @Evolutious want to rework parts to use this, feel free to make a pull request with your edits, or discuss details here like ways to rebuild configurable seconds-based settings to use GCDs.

**Comment by Evolutious** [comment]
All I did was add `double gcd = ActionManager.GetAdjustedRecastTime(ActionType.Spell, actionID) / 1000f;` to the top of each class combo then i reference `gcd` when i need to do something that is based on the gcd, like this for example:

```
if (!gauge.BeastChakra.Contains(BeastChakra.RAPTOR)) {
	return (level < MNK.Levels.TwinSnakes || SelfEffectDuration(MNK.Buffs.DisciplinedFist) <= (gcd * 3))
		? MNK.TrueStrike
		: MNK.TwinSnakes;
}
if (!gauge.BeastChakra.Contains(BeastChakra.COEURL)) {
	return (level < MNK.Levels.Demolish || TargetFindOwnEffect(MNK.Debuffs.Demolish)?.RemainingTime >= (gcd * 3))
		? MNK.SnapPunch
		: MNK.Demolish;
}
```

so, where normally you would be specifying a fixed number or provide a variable slider, you just do a multiple of gcd instead (which is what you should be doing anyways)

**Comment by vitharr137** [comment]
I am still working on the timing and bugfixing the rotation in my potential PR. For longer combos, the base GCD seems to work well, but for closer casts like simple dot maintenance for healers for instance, I'm using a more fine tuned approach with a combination of CooldownRemaining and the new GCD calculation. There is also a need occasionally to account for travel time or exceedingly long delays between keypress and application, such as Demolish once again. So far a buffer of .69 amusingly is the closest I can push the delay and have it not fall off. All in all it's coming together very nicely, though

```
double gcd = ActionManager.GetAdjustedRecastTime(ActionType.Spell, BRD.HeavyShot) / 1000f;
double remainingGCD = GetCooldown(BRD.HeavyShot).CooldownRemaining;
double totalGCD = remainingGCD + gcd;
double maintGCD = remainingGCD + gcd + 0.69f;
```
