### ISSUE TITLE
Replacer requests and incorrect combos

### ISSUE THREAD

**Issue by PrincessRTFM** [PrincessRTFM/XIVComboPlugin#8]
> Since i have everything unlocked to at least level 80 (with Pld, Sch, Sge, Smn at 90, reaper at 86), i went about testing all of them
> 
> Prefered additions:
> Sage - A phlegma into Dyskrasia option when its out of stacks would be great
> Reaper - Only thing it needs is an automatic switch to Gluttony if its off cooldown
> 
> Jobs with issues
> 
> Summoner - Both tri-disaster  *and* ruin become x rite, when tri-disaster should become x Catastrophe instead
> Bard - Truthfully im a bit confused regarding the endwalker bard changes, but when all the options are enabled, hitting Rain of death and Bloodletter becomes much harder since they get replaced even when they have charges
> 
> Otherwise, every other job works fine at least at level 80. (The only one i didn't test is monk, partly because the new changes confuse me)
> 
> Apologies for not responding sooner - I was asleep

_Originally posted by @AwesomeJames2120 in https://github.com/PrincessRTFM/XIVComboPlugin/issues/7#issuecomment-1001883218_

**Comment by PrincessRTFM** [comment]
For Bard, I just looked into it and I'm not sure why it's acting like that, although I don't play Bard personally, so I don't understand the changes well either. At the moment, I'm considering that it may be something to do with the charges that are causing the bug, but I just don't know right now.

Looking around, I see that daemitus's fork (which mine is based on) has that particular feature disabled, and I suspect this is why. Until I can figure out what's causing the issue (or someone else does) I think I'm going to have to do the same. That combo will be removed in the next update.

-----

For Summoner, I found the problem (typos, basically) and went through the relevant sections, it should be fixed and working properly on next release.

-----

For Sage, I haven't found a way to check the number of charges on an action, so unless I'm misunderstanding the request, I can't actually implement that yet. If I find a way, I'll be sure to add it!

For Reaper, what specifically should change into Gluttony when it's off CD? Keep in mind that I don't (yet) play Reaper myself.

**Comment by AwesomeJames2120** [comment]
For Reaper, Blood Stalk, Grim Swathe (and *probably* unveiled gibbet and unveiled gallows) are the ones that should be swapped for gluttony

As for checking the number of charges, Grammernatzi got it to work in their fork, so you could probably copy what they did https://github.com/Grammernatzi/XIVComboPluginExpandedest

**Comment by PrincessRTFM** [comment]
I can't find anything in their fork dealing with action charges. If you mean the replacer for Empyreal Arrow to Sidewinder, that only turns EA into Sidewinder when EA's on CD and Sidewinder isn't, which is functionally different than the Bloodletter one. I could port that over, but it wouldn't be the same thing.

For Reaper, I'm implementing those four options now, with separate settings for each of them. They'll be available in the next build, which should be up shortly.

**Comment by AwesomeJames2120** [comment]
Nah nah, i meant the part of their sage changes where "Phlegma turns into Toxikon if you are out of charges"

**Comment by PrincessRTFM** [comment]
It looks, from the section you mentioned and the official job guide page for sage, like the cooldown timer that's returned in the code is actually the time until the action is _fully_ ready, in the case of moves with charges. I want to do some testing to verify that, but if it's right, that certainly has some possibilities, including the one you mentioned.

**Comment by AwesomeJames2120** [comment]
Dark knight issue: The 'Salty Shadowbringer' combo worked great until I reached level 86 and gained the salt and darkness ability, which then rendered it non functional as it started using salt and darkness instead of salted earth, despite salt and darkness requiring salted earth to be active for it to function.

Since the game automatically swaps salted earth with salt and darkness anyway by default, this should probably be an easy fix

**Comment by PrincessRTFM** [comment]
If the only issue is that it turns explicitly into SaD when it shouldn't, that's real easy, yeah. As long as the rest of the replacer makes sense, this is a five-minute fix, since I already have the code up.

**Comment by PrincessRTFM** [comment]
Three minutes, apparently! Pushed, should be ready shortly. I'm leaving this open because of the SGE bit earlier up though. @me for future reference:
> Sage - A phlegma into Dyskrasia option when its out of stacks would be great
see also:
> the cooldown timer that's returned in the code is actually the time until the action is fully ready, in the case of moves with charges
I haven't gotten a chance to test that bit yet, life's been happening, but it's still a work-in-progress and I haven't forgotten!

**Comment by AwesomeJames2120** [comment]
I just got Dark knight up to 90 to see if the Shadowbringer part of the aforementioned salty shadowbringer combo worked correctly, and it almost does, it just needs a bit of tweaking

The main issue with it currently is that it seems to treat it as if its not an ability with two charges, and instead switches to salted earth immediately after use, then back to carve and spit/Abyssal Drain, even though they aren't usable yet even though shadowbringer is available.

An easy solution to fix this would *probably* be to have it switch back to shadowbringer while cave and spit/abyssal drain are on cooldown, then switch back to them when they're ready. (and even better, have it available after salt and darkness is used)

**Comment by undercaffeinated** [comment]
Fire 2 Feature doesn't seem to be working, using the AoE rotation down to <1 umbral heart, high fire 2 doesn't get replaced by flare

**Comment by PrincessRTFM** [comment]
I'm not sure why HF2 isn't replacing, since a look at the code tells me that if anything _normal_ F2 should've been broken. Either way, I've made a change that _might_ fix it, but I'm not sure, since I don't have BLM at 82 to test it.

The DRK problem is almost certainly because it's only looking at cooldowns, and can't properly detect charges. It's trying to give you "whatever has the least cooldown time remaining". Clearly, that logic doesn't work with multi-charge actions. Unfortunately, I don't have DRK at 90, so I can't test anything on that one myself. I'll see if one of my friends is able to run some test builds once I can get them together.

I know it's been a couple of days already, sorry about that - life is happening and also I burned out after a solid week of nothing but XIV. This project is still alive, and I _will_ get the updates made!

**Comment by AwesomeJames2120** [comment]
By all means take your time gamer, what you've done thus far with this thing is fantastic already

**Comment by PrincessRTFM** [comment]
Yeah, I think I'm gonna go with the suggestion to have Flood/Edge of Darkness become Shadowbringer while under Darkside with <6k MP. Honestly, the actions are different enough that the original didn't _really_ make sense to me, but I've never played DRK.

@AwesomeJames2120 any reason you said 6k MP instead of 3k, which is the cost for Flood/Edge?

**Comment by PrincessRTFM** [comment]
GDI, that was supposed to be a feature not a bug :v
