### ISSUE TITLE
6.4 update broke SigScanner

### ISSUE THREAD

**Issue by Evolutious** [PrincessRTFM/XIVComboPlugin#81]
Looks like the static address you are using for ComboTimer is no longer valid. Curious, how do you find out what it changes to?

![Screenshot 2023-05-24 160458](https://github.com/PrincessRTFM/XIVComboPlugin/assets/49498530/53acc01c-e6e0-43e4-b7f5-eab4519bba50)

**Comment by howlingc** [comment]
Here are the new sigs for ComboTimer and GetAdjustedActionId. Tested them on a dev build, and they work.

            this.ComboTimer = scanner.GetStaticAddressFromSig("F3 0F 11 05 ?? ?? ?? ?? 48 83 C7 08");

            this.GetAdjustedActionId = scanner.ScanText("E8 ?? ?? ?? ?? 89 03 8B 03");

**Comment by Evolutious** [comment]
Confirmed! Updated and everything is good now.

How do you get these?

**Comment by howlingc** [comment]
Dunno, havent' gotten that far with my dabling with plugins yet. :)  
Someone else did the work on finding them, and I'm just passing the info.

**Comment by Evolutious** [comment]
Cheers! Thanks for sharing!
