### ISSUE TITLE
WAR combo suggestion

### ISSUE THREAD

**Issue by Theletha** [PrincessRTFM/XIVComboPlugin#82]
Hi i love that you now have added more of the ogcd abilities to the rotation and it is very nice. 
I have been using it for a while and at this moment the only thing that is a bit wrong is that it wants to use upheaval before Surging Tempest buff is active, this is usually a problem during the openers. Same goes for the AoE rotation with upheavals equivalent ability.

To remedy this maybe it won't priorities upheaval until Surging Tempest buff is active.

![image](https://github.com/PrincessRTFM/XIVComboPlugin/assets/10131942/5f34f2a7-9019-4836-8f2a-9ef38a7e51d8)

**Comment by PrincessRTFM** [comment]
This sounds simple, but just to be sure: all you want is to move the Surging Tempest buff before Upheaval? I take it this is part of the standard rotation?

**Comment by Theletha** [comment]
exactly so Upheaval and Orogeny (shares cd) shouldn't be queued if Surging Tempest buff isn't active. That way i can complete the correct rotation :)

**Comment by PrincessRTFM** [comment]
Upheaval is done on weaving, so it doesn't replace Storm's Eye. When running your rotation, just don't weave it in until you have the buff.

**Comment by PrincessRTFM** [comment]
Added a new option to prevent weaving Upheaval without the buff anyway, but you can really just do this by not pressing the button again

**Comment by Theletha** [comment]
Dude, it's just perfect now. Thanks for the quick implementation and amazing work. Now i can do the full rotation smoothly! 

Thanks!
