### ISSUE TITLE
Paladin Divine Might

### ISSUE THREAD

**Issue by PetalTempest** [PrincessRTFM/XIVComboPlugin#83]
Hello!
I was wondering if you would consider adding an option for Paladin to change Royal Authority into Holy Spirit, and Prominence into Holy Circle, when the Divine Might buff is active.

The priority would be lower than the Requiescat combo but higher than Atonement. 

So for single target it would look something like:
Requiescat combo > Holy Spirit (with Divine Might) > Atonement > Royal Authority combo

Then for AoE it would be:
Requiescat combo > Holy Circle (with Divine Might) > Prominence combo.

Thank you for your consideration! 
[<a href="https://imgur.com/cWtWr76"><img src="https://i.imgur.com/cWtWr76.png" title="source: imgur.com" /></a>](url)

**Comment by PrincessRTFM** [comment]
In both cases, the existing normal combo chain is prioritised _if_ it's already in progress; if you've done the first action then even if Divine Might is up it will continue the chain until it's finished. This is to save the chain (with the potency increase) because Divine Might lasts half a minute and HS/HC are both spells so they'll probably break the chain.

**Comment by PetalTempest** [comment]
Surprisingly enough it doesn't break the combo. Nothing does except switching from the Royal Authority combo to the Prominence combo; but if you still think it's best not to implement I understand. I appreciate the consideration.

**Comment by PrincessRTFM** [comment]
I don't play paladin; this was chosen purely on the basis of thinking it might break the chain and wanting to avoid that. I don't know which way is "best" to actually _use_. If any paladin mains come in and tell me that it should actually be the other way around, I can easily reorder the checks. If you find anything pointing at that, you can comment here and I'll change it.

**Comment by PetalTempest** [comment]
This is from The Balance. 
If you're not familiar, it's a website/discord that focuses on theorycrafting and optimizing rotations.
In this graphic you can see Holy Spirit with Divine Might is the top priority "Filler" ability.
![image](https://github.com/PrincessRTFM/XIVComboPlugin/assets/109507817/b01dfd08-22db-484b-953e-def418c5d83d)

**Comment by PrincessRTFM** [comment]
Should be easy enough. If there's no reason to hold it until the combo ends, I'll just shift those two pieces up a little when I have the chance.

**Comment by PetalTempest** [comment]
Thank you so much! 

![AS5rBfC](https://github.com/PrincessRTFM/XIVComboPlugin/assets/109507817/04d6af06-df8a-4850-b768-4154e08e600f)

**Comment by PetalTempest** [comment]
Oh my gosh, I'm **SO** sorry.
I thought your original reply meant you weren't going to implement the feature. 
Please forgive my misunderstanding.
It works perfectly as is.
Thank you sooooooo much!
