### ISSUE TITLE
SCH - Art of war

### ISSUE THREAD

**Issue by naTlatsyrC** [PrincessRTFM/XIVComboPlugin#87]
Could the "Lucid Ruin & Broil" [debug:2811] function be applied to "Art of war" aswell?

If possible have its own MP threshold it waits for before switching it, thanks!

**Comment by PrincessRTFM** [comment]
Yes, that should be pretty easy to add. Life's just been extremely busy this last month (and probably will continue to be for several weeks), sorry about the delay.
