### ISSUE TITLE
Astrologian's Draw Lockout

### ISSUE THREAD

**Issue by Herbalicious** [PrincessRTFM/XIVComboPlugin#88]
Placing Malefic on top of Draw doesn't make a lot of sense to me. I think locking it out with Redraw (if the player has the buff `Clarifying Draw`) would make a lot more sense, as there is **zero** situation an AST would want to cast Draw if Redraw is available. I've been running a macro for _years_ that essentially does this, and I can't imagine ever playing without it.

Thanks for the consideration. 👍

**Comment by PrincessRTFM** [comment]
As someone who doesn't play AST, I'll defer to someone who does. To be clear, you want to have Draw replaced with Redraw when under the Clarifying Draw buff? I'll leave the existing combo in place because some people might be using it, but I can add a new one with higher priority to do that.

**Comment by Herbalicious** [comment]
Exactly. Literally all the buff means is "You can cast Redraw", so just a blanket replacement of Draw with Redraw as long as you have the buff would be perfect.
