### ISSUE TITLE
False Positive multiple combo plugin detection

### ISSUE THREAD

**Issue by JohnRCrichton** [PrincessRTFM/XIVComboPlugin#90]
I only have XIV Combo Very Expanded installed, however it's registering itself as two different plugin names. XIVComboVX and XIV Combo Very Expanded.

Message given:
You appear to have installed 1 other combo plugin as well as XIVComboVX. This is generally considered a Very Bad Idea. Running more than one combo plugin is known to cause problems with your game as they fight each other for control.
For your safety, XIVComboVX has automatically disabled itself and only registered its custom /pcombovx command to allow the other combo plugin to use /pcombo instead.
If you are determined to use multiple combo plugins at once, no support will be provided but you can open XIVComboVX's settings and re-enable it from the menu bar.
However, you are very strongly recommended to disable the all except one of your 2 combo plugins: XIVComboVX, XIV Combo Very Expanded
If this is a false positive, please open a report on the issue tracker with the plugin name.

**Comment by Tenrys** [comment]
I'm also having this issue.

**Comment by dzfawks221** [comment]
same issue, in some cases after loading none of the combos are being triggered unless the plugin is reloaded first.

**Comment by Electrized** [comment]
Deleted all other repos including even deprecated versions of combo plugins, deleted all configs for them aswell, still having a false positive.
![image](https://github.com/PrincessRTFM/XIVComboPlugin/assets/29844497/304d91b3-0fb5-4ab3-84a9-4b567d531733)

**Comment by PrincessRTFM** [comment]
Well that's unexpected. Gonna push a quick patch to disable the check then dig into this.

**Comment by PrincessRTFM** [comment]
Oh I bet I know what I did wrong... man, I feel dumb.

**Comment by PrincessRTFM** [comment]
Yeah. When trying to filter all installed plugins to not match against itself, I was comparing internal ID against display name, which obviously isn't gonna work. Mea culpa, sorry all!

**Comment by PrincessRTFM** [comment]
Should be fixed now. I've pushed another updating turning it back on again.
