### ISSUE TITLE
Soft Target Phlegma Gap Closer

### ISSUE THREAD

**Issue by vaoan** [PrincessRTFM/XIVComboPlugin#91]
Phlegma Gap Closer:

- [x] Adding **Soft Targgeting** for this feature so it's controller friendly
- [x] When Targetting or soft-targetting an **ally**, have a **different range** for phlegma to turn into Icarus
- [x] **_(BUG)_** When Phlegma's 2 charges have been used, it doesn't transform into Icarus when passing the configured range.

Flying Phlegma:

- [x] When Phlegma is on 0 charges, add a range check of 1 from the target or soft target before transforming Icarus back. Reason for this: Using Phlegma in the opener makes easy to waste Icarus when trying to queue skills by spamming the Phlegma button.

**Comment by PrincessRTFM** [comment]
I'm adding the soft targeting feature to _all_ combos by just tweaking the method used to acquire the current target, since that's a good idea that I overlooked (on account of not using a controller)
