### ISSUE TITLE
Swiftcast into Rezz Skill for all available rezzers when swiftcast buff is active

### ISSUE THREAD

**Issue by vaoan** [PrincessRTFM/XIVComboPlugin#93]
- [ ] Option to transform Swifcast into Egeiro/VerRaise/Raise/Ascend/Resurrection if Swiftcast buff is active. 

Reason why, is usually more important to know the timing of your swiftcast than having an active rezz button you might not even use the entire fight

**Comment by PrincessRTFM** [comment]
I've seen several fights that were only saved because of hardcasting a rezz. I think it'd be a better idea to use a cooldown tracking plugin, or put swiftcast somewhere on a hotbar, or just not use the combo.
